FROM nvcr.io/nvidia/cuda:11.3.1-cudnn8-runtime-ubuntu20.04
LABEL maintainer="nlkey2022@gmail.com"

RUN DEBIAN_FRONTEND=noninteractive apt-get -qq update \
 && DEBIAN_FRONTEND=noninteractive apt-get -qqy install curl python3-pip git \
 && rm -rf /var/lib/apt/lists/*

ARG WEIGHT="1YrkwfM-0VBCJaa9NYaXUQPODdGPsmQY4"

RUN git clone https://github.com/sisyphus192/ai-docstring.git /app/ai-docstring \
    && cd /app/ai-docstring/server

WORKDIR /app/ai-docstring/server

RUN pip3 install torch==1.9.0+cu111 torchvision==0.10.0+cu111 -f https://download.pytorch.org/whl/torch_stable.html
RUN pip3 install gdown
RUN gdown https://drive.google.com/uc?id=${WEIGHT}

RUN pip3 install -r requirements.txt

ENTRYPOINT ["python3", "app.py"]